---
- hosts: bigip1
  gather_facts: false
  connection: local
  vars_files:
    - ./udf_infra.yml
    - ./as3_settings.yml
    - ./secrets.yml
  roles:
    - ipam_phpipam
    - dns_powerdns
    - cert_cfssl
    - bigip_as3_deploy
    - summary