version: "3"

services:
  web-app:
    image: f5devcentral/f5-demo-httpd:nginx
    restart: unless-stopped
    environment:
      - F5DEMO_APP=website
      - F5DEMO_NODENAME='UDF HTTP Pool Member'
      - F5DEMO_COLOR=ffd734
      - F5DEMO_NODENAME_SSL='UDF HTTPS Pool Member'
      - F5DEMO_COLOR_SSL=a0bf37
    ports:
      - "80"
      - "443"
