---
- name: Manage Application Services with AS3
  block:
    - debug:
        msg: "{{ lookup('template', 'templates/' + as3_template + '.j2') }}"
        
    - bigip_appsvcs_extension:
        content: "{{ lookup('template', 'templates/' + as3_template + '.j2') }}"
        provider: "{{ bigip_provider }}"
  when: as3_state == "present"

- name: Remove Application Services with AS3
  block:
    - bigip_appsvcs_extension:
        provider: "{{ bigip_provider }}"
        content: "{{ lookup('template', 'templates/AS3-delete-tenant.j2') }}"
  when: as3_state == "absent"
