---
- hosts: local
  connection: local
  collections:
   - F5solutionsengineering.ss_cat
  vars_files:
    - ./udf_infra.yml
    - ./secrets.yml
  vars:
    - application_state: present
    - application_fqdn: "{{ application_name }}"
    - application_sans:
      - "{{ application_fqdn }}"
      - "{{ application_name.split('.')[0] }}"
    - application_tenant: "{{ 'tenant-' + application_name }}" #ex. tenant-app1
    - application_template: AS3-httpsv2
    - application_member_type: address
  roles:
    - ipam_phpipam
    - cert_cfssl
    - bigip_as3_deploy