---
- hosts: local
  connection: local
  vars_files:
    - ./udf_infra.yml
    - ./secrets.yml
  vars:
    - application_state: present
    - application_fqdn: "{{ application_name }}"
    - application_sans:
      - "{{ application_fqdn }}"
      - "{{ application_name.split('.')[0] }}"
    - application_tenant: "{{ 'tenant-' + application_name }}" #ex. tenant-app1
    - application_template: AS3-httpsv2
    - application_member_type: address
  roles:
    - infoblox-ipam
    - cfssl-cert
    - bigip-as3-deploy