---
validate_certs: false
cfssl_common_name: "{{ application_fqdn }}"
cfssl_hosts:
  - "{{ application_fqdn }}"
  - "{{ application_name.split('.')[0] }}"
cfssl_state: "{{ deployment_state|default('present') }}"